//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VkLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VkLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VK.VkLocalization", typeof(VkLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the group is denied.
        /// </summary>
        public static string AccessToGroupDenied {
            get {
                return ResourceManager.GetString("AccessToGroupDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token has expired.
        /// </summary>
        public static string AccessTokenHasExpired {
            get {
                return ResourceManager.GetString("AccessTokenHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token was not provided.
        /// </summary>
        public static string AccessTokenNotProvided {
            get {
                return ResourceManager.GetString("AccessTokenNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to subscriptions or followers list denied.
        /// </summary>
        public static string AccessToSubscriptionsDenied {
            get {
                return ResourceManager.GetString("AccessToSubscriptionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acoustic &amp; Vocal.
        /// </summary>
        public static string AcousticAndVocal {
            get {
                return ResourceManager.GetString("AcousticAndVocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All genres.
        /// </summary>
        public static string AllGenres {
            get {
                return ResourceManager.GetString("AllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks.
        /// </summary>
        public static string AllTracks {
            get {
                return ResourceManager.GetString("AllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is disabled, enable your application or use test mode.
        /// </summary>
        public static string ApplicationIsDisabled {
            get {
                return ResourceManager.GetString("ApplicationIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is expired.
        /// </summary>
        public static string CacheExpired {
            get {
                return ResourceManager.GetString("CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is needed.
        /// </summary>
        public static string CaptchaIsNeeded {
            get {
                return ResourceManager.GetString("CaptchaIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanson.
        /// </summary>
        public static string Chanson {
            get {
                return ResourceManager.GetString("Chanson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical.
        /// </summary>
        public static string Classical {
            get {
                return ResourceManager.GetString("Classical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance &amp; House.
        /// </summary>
        public static string DanceAndHouse {
            get {
                return ResourceManager.GetString("DanceAndHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum &amp; Bass.
        /// </summary>
        public static string DrumAndBass {
            get {
                return ResourceManager.GetString("DrumAndBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubstep.
        /// </summary>
        public static string Dubstep {
            get {
                return ResourceManager.GetString("Dubstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Listening.
        /// </summary>
        public static string EasyListening {
            get {
                return ResourceManager.GetString("EasyListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electropop &amp; Disco.
        /// </summary>
        public static string ElectropopAndDisco {
            get {
                return ResourceManager.GetString("ElectropopAndDisco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic.
        /// </summary>
        public static string Ethnic {
            get {
                return ResourceManager.GetString("Ethnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood control enabled for this action.
        /// </summary>
        public static string FloodControlIsEnabled {
            get {
                return ResourceManager.GetString("FloodControlIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect signature.
        /// </summary>
        public static string IncorrectSignature {
            get {
                return ResourceManager.GetString("IncorrectSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie.
        /// </summary>
        public static string IndiePop {
            get {
                return ResourceManager.GetString("IndiePop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental.
        /// </summary>
        public static string Instrumental {
            get {
                return ResourceManager.GetString("Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group id.
        /// </summary>
        public static string InvalidGroupId {
            get {
                return ResourceManager.GetString("InvalidGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input parameters.
        /// </summary>
        public static string InvalidInputParameters {
            get {
                return ResourceManager.GetString("InvalidInputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message.
        /// </summary>
        public static string InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the parameters specified was missing or invalid.
        /// </summary>
        public static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid score.
        /// </summary>
        public static string InvalidScore {
            get {
                return ResourceManager.GetString("InvalidScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz &amp; Blues.
        /// </summary>
        public static string JazzAndBlues {
            get {
                return ResourceManager.GetString("JazzAndBlues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        public static string Metal {
            get {
                return ResourceManager.GetString("Metal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameters were found in response from VK server.
        /// </summary>
        public static string NoMatchesFoundInResponse {
            get {
                return ResourceManager.GetString("NoMatchesFoundInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required parameters were found in response from VK server.
        /// </summary>
        public static string NotAllRequiredMatchesFoundInResponse {
            get {
                return ResourceManager.GetString("NotAllRequiredMatchesFoundInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to perform this action is denied by user.
        /// </summary>
        public static string PermissionDeniedByUser {
            get {
                return ResourceManager.GetString("PermissionDeniedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string Pop {
            get {
                return ResourceManager.GetString("Pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rap &amp; Hip-Hop.
        /// </summary>
        public static string RapAndHipHop {
            get {
                return ResourceManager.GetString("RapAndHipHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reggae.
        /// </summary>
        public static string Reggae {
            get {
                return ResourceManager.GetString("Reggae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests per second.
        /// </summary>
        public static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trance.
        /// </summary>
        public static string Trance {
            get {
                return ResourceManager.GetString("Trance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error code: {0}.
        /// </summary>
        public static string UnknownErrorCode {
            get {
                return ResourceManager.GetString("UnknownErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred.
        /// </summary>
        public static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown method passed.
        /// </summary>
        public static string UnknownMethodPassed {
            get {
                return ResourceManager.GetString("UnknownMethodPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to users audio is denied.
        /// </summary>
        public static string UserAudiosAccessDenied {
            get {
                return ResourceManager.GetString("UserAudiosAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authorization failed.
        /// </summary>
        public static string UserAuthorizationFailed {
            get {
                return ResourceManager.GetString("UserAuthorizationFailed", resourceCulture);
            }
        }
    }
}
