//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VkResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VkResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VK.VkResource", typeof(VkResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the group is denied.
        /// </summary>
        internal static string AccessToGroupDenied {
            get {
                return ResourceManager.GetString("AccessToGroupDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to subscriptions or followers list denied.
        /// </summary>
        internal static string AccessToSubscriptionsDenied {
            get {
                return ResourceManager.GetString("AccessToSubscriptionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is disabled, enable your application or use test mode.
        /// </summary>
        internal static string ApplicationIsDisabled {
            get {
                return ResourceManager.GetString("ApplicationIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache is expired.
        /// </summary>
        internal static string CacheExpired {
            get {
                return ResourceManager.GetString("CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha is needed.
        /// </summary>
        internal static string CaptchaIsNeeded {
            get {
                return ResourceManager.GetString("CaptchaIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood control enabled for this action.
        /// </summary>
        internal static string FloodControlIsEnabled {
            get {
                return ResourceManager.GetString("FloodControlIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect signature.
        /// </summary>
        internal static string IncorrectSignature {
            get {
                return ResourceManager.GetString("IncorrectSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid group id.
        /// </summary>
        internal static string InvalidGroupId {
            get {
                return ResourceManager.GetString("InvalidGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input parameters.
        /// </summary>
        internal static string InvalidInputParameters {
            get {
                return ResourceManager.GetString("InvalidInputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message.
        /// </summary>
        internal static string InvalidMessage {
            get {
                return ResourceManager.GetString("InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the parameters specified was missing or invalid.
        /// </summary>
        internal static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid score.
        /// </summary>
        internal static string InvalidScore {
            get {
                return ResourceManager.GetString("InvalidScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user id.
        /// </summary>
        internal static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches were found in response from VK server.
        /// </summary>
        internal static string NoMatchesFoundInResponse {
            get {
                return ResourceManager.GetString("NoMatchesFoundInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required matches were found in response from VK server.
        /// </summary>
        internal static string NotAllRequiredMatchesFoundInResponse {
            get {
                return ResourceManager.GetString("NotAllRequiredMatchesFoundInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to perform this action is denied by user.
        /// </summary>
        internal static string PermissionDeniedByUser {
            get {
                return ResourceManager.GetString("PermissionDeniedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests per second.
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error code: {0}.
        /// </summary>
        internal static string UnknownErrorCode {
            get {
                return ResourceManager.GetString("UnknownErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred.
        /// </summary>
        internal static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown method passed.
        /// </summary>
        internal static string UnknownMethodPassed {
            get {
                return ResourceManager.GetString("UnknownMethodPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authorization failed.
        /// </summary>
        internal static string UserAuthorizationFailed {
            get {
                return ResourceManager.GetString("UserAuthorizationFailed", resourceCulture);
            }
        }
    }
}
